'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Componentes
    Public Property ComponenteID As Integer
    Public Property PlantillaID As Integer
    Public Property NombreComponente As String
    Public Property Codigo As String
    Public Property XTabla As Nullable(Of Boolean)

End Class
