'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Plantillas
    Public Property PlantillaID As Integer
    Public Property TecnologiaID As Integer
    Public Property NombrePlantilla As String
    Public Property Orden As Nullable(Of Integer)

End Class
