'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProyectosYTecnologias
    Public Property ProyectosYTecnologiasID As Integer
    Public Property ProyectoID As Integer
    Public Property TecnologiaID As Integer
    Public Property PlantillaID As Integer

End Class
