'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TablasRelacionadas
    Public Property RelacionTablasID As Integer
    Public Property ID_TablaDependiente As Integer
    Public Property ID_CampoDependiente As Integer
    Public Property ID_TablaINDEPENDIENTE As Integer
    Public Property ID_CampoINDEPENDIENTE As Integer

End Class
